allow disabling the generation of the self-signed certificates
Allow the commit moves the genreration of the certificate at runtime
(rather than at build-time). This allows taking into account the value
of SHANOIR_URL_HOST.

diff --git a/docker-compose/users/entrypoint b/docker-compose/users/entrypoint
--- a/docker-compose/users/entrypoint
+++ b/docker-compose/users/entrypoint
@@ -22,6 +22,49 @@ auto|init)
 esac
 
 
+# TLS server certificate management
+# ---------------------------------
+#
+# SHANOIR_CERTIFICATE my have two possible values:
+#
+# - auto   (for development) -> shanoir automatically generates a self-signed certificate
+# - manual (for production)  -> certificate is provided by the sysadmin
+#
+# Notes: 
+#  - the cert generation is performed in the 'users' container because it is the first one to be
+#    started (all other containers needing this cert are launched afterwards)
+#  - in mode 'auto' the certificate is also automatically re-generated when the value of
+#    SHANOIR_URL_HOST changes
+keystore="/etc/ssl/certs/java/cacerts"
+crt="/etc/ssl/certs/java/shanoir-ng-nginx.crt"
+key="/etc/ssl/certs/java/shanoir-ng-nginx.key"
+
+match  SHANOIR_CERTIFICATE '^(auto|manual)$'
+case "$SHANOIR_CERTIFICATE" in
+manual)
+	[ -f "$crt"      ] || error "missing pem certificate: $crt"
+	[ -f "$keystore" ] || error "missing java keystore: $keystore"
+	;;
+auto)
+	if [ ! -f "$crt" ] || [ "`openssl x509 -in "$crt"  -subject|grep ^subject=`" \
+				!= "subject=CN = $SHANOIR_URL_HOST" ]
+	then
+		echo "generating a self-signed certificate with CN=$SHANOIR_URL_HOST..."
+		openssl genrsa 2048 > /tmp/key
+		openssl req -new -key /tmp/key -out /tmp/csr -batch -subj "/CN=$SHANOIR_URL_HOST"
+		openssl x509 -req -days 730 -in /tmp/csr -signkey /tmp/key -out /tmp/crt
+		rm -f /tmp/store
+		# FIXME: does the alias need to match the host name ?
+		keytool -importcert -file /tmp/crt -alias shanoir-ng-nginx -keystore /tmp/store \
+			-storepass changeit -noprompt -trustcacerts
+		mv /tmp/store "$keystore"
+		mv /tmp/key   "$key"
+		mv /tmp/crt   "$crt"
+	fi
+	;;
+esac
+
+
 abort_if_error
 
 run_microservice "$@" "$sync"
