improve 'oneshot' ergonomy
- report an error if no patterns are provided
- display a report before exiting (listing which pattern
  was matched/not-matched)

diff --git a/utils/oneshot b/utils/oneshot
--- a/utils/oneshot
+++ b/utils/oneshot
@@ -39,6 +39,11 @@ while [ "$1" != "--" ] ; do
 done
 shift
 
+if [ ${#patterns[@]} -eq 0 ] ; then
+	echo "oneshot: error: must provide at least one pattern" >&2
+	exit 100
+fi
+
 # run the command with its outputs redirected to a fifo
 
 fifo="`tmp_fifo`"
@@ -66,6 +71,13 @@ while read -r line ; do
 done <"$fifo"
 
 # eof
+
+echo "  ------------------- match report --------------------------"
+i=0
+for pattern in "${patterns[@]}" ; do
+	[ $((i++)) -lt $current ] && status="\e[32m OK \e[39m" || status="\e[31mFAIL\e[39m"
+	echo "  [ `echo -e "$status"` ]  $pattern"
+done
 
 wait "$pid" || true
 
